on:
  workflow_dispatch:
  pull_request:
    master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: pip install -e .[dev]
    - run: flake8 .

  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: pip install -e .[dev]
    - run: mypy .
